name: neville
recipe: platformsh
config:
  id: mm3lcf5ygjhvq
proxy:
  node:
    - bs.neville.lndo.site:3000
  app:
    - neville.lndo.site
services:
  node:
    type: node
    build:
      - npm install
      # - gulp
    globals:
      gulp-cli: latest
    # command: cd /app/web/themes/custom/discovery && gulp watch
tooling:
  npm:
    service: node
  node:
    service: node
  gulp:
    service: node
