name: neville
recipe: platformsh
config:
  id: mm3lcf5ygjhvq
services:
  node:
    type: node
    build:
      - npm install
      # - gulp
    globals:
      gulp-cli: latest
# ssl: true
# command: cd /app/web/themes/custom/ discovery && lando gulp watch
tooling:
  npm:
    service: node
  node:
    service: node
  gulp:
    service: node
  # yarn:
  #   service: node
proxy:
  app:
    - neville.lndo.site
