name: neville
recipe: platformsh
config:
  id: mm3lcf5ygjhvq
proxy:
  app:
    - neville.lndo.site
services:
  node:
    type: node
    build:
      - npm install
    globals:
      gulp-cli: latest
    port: 3000
    ssl: 4444
tooling:
  npm:
    service: node
  node:
    service: node
  gulp:
    service: node
  drush:
    service: app
    env:
      DRUSH_OPTIONS_URI: "https://neville.lndo.site"
