<?php

/**
 * @file
 * Contains as_dept_people_stub.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\taxonomy\Entity\Term;

/**
 * Implements hook_help().
 */
function as_dept_people_stub_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the as_dept_people_stub module.
    case 'help.page.as_dept_people_stub':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Contains migrations to import people stubs from people.as.cornell.edu to departments.as.cornell.edu') . '</p>';
      return $output;

    default:
  }
}


/**
 * Transforms department name to domain id.
 */


function as_dept_people_stub_map_dept_domain($deptname) {
      $termids = \Drupal::entityQuery('taxonomy_term')
        ->condition('vid', 'departments_programs')
        ->condition('name', $deptname)
        ->execute();
        if (!empty($termids)){
          foreach($termids as $tid)
            {
              $term = Term::load($tid);
              $domainid = $term->get('field_domain_access_target_id')->value;
            }
          }
        return $domainid;
}
