# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by Platform.sh.

"https://departments.as.cornell.edu/":
    type: upstream
    upstream: "app:http"
    cache:
      enabled: true
      # Base the cache on the session cookie and custom Drupal cookies. Ignore all other cookies.
      cookies: ['/^SS?ESS/', '/^Drupal.visitor/']
"https://dept1.as.cornell.edu/":
    type: upstream
    upstream: "app:http"
    cache:
      enabled: true
      cookies: ['/^SS?ESS/', '/^Drupal.visitor/']
"https://dept2.as.cornell.edu/":
    type: upstream
    upstream: "app:http"
    cache:
      enabled: true
      cookies: ['/^SS?ESS/', '/^Drupal.visitor/']
"https://dept3.as.cornell.edu/":
    type: upstream
    upstream: "app:http"
    cache:
      enabled: true
      cookies: ['/^SS?ESS/', '/^Drupal.visitor/']
"https://dept4.as.cornell.edu/":
    type: upstream
    upstream: "app:http"
    cache:
      enabled: true
      cookies: ['/^SS?ESS/', '/^Drupal.visitor/']
"https://dept5.as.cornell.edu/":
    type: upstream
    upstream: "app:http"
    cache:
      enabled: true
      cookies: ['/^SS?ESS/', '/^Drupal.visitor/']
"https://americanstudies.as.cornell.edu/":
    type: upstream
    upstream: "app:http"
    cache:
      enabled: true
      cookies: ['/^SS?ESS/', '/^Drupal.visitor/']
"https://anthropology.as.cornell.edu/":
    type: upstream
    upstream: "app:http"
    cache:
      enabled: true
      cookies: ['/^SS?ESS/', '/^Drupal.visitor/']
"https://asianstudies.as.cornell.edu/":
    type: upstream
    upstream: "app:http"
    cache:
      enabled: true
      cookies: ['/^SS?ESS/', '/^Drupal.visitor/']
"https://chemistry.as.cornell.edu/":
    type: upstream
    upstream: "app:http"
    cache:
      enabled: true
      cookies: ['/^SS?ESS/', '/^Drupal.visitor/']
"https://ecologyandevolution.as.cornell.edu/":
    type: upstream
    upstream: "app:http"
    cache:
      enabled: true
      cookies: ['/^SS?ESS/', '/^Drupal.visitor/']
"https://economics.as.cornell.edu/":
    type: upstream
    upstream: "app:http"
    cache:
      enabled: true
      cookies: ['/^SS?ESS/', '/^Drupal.visitor/']
"https://government.as.cornell.edu/":
    type: upstream
    upstream: "app:http"
    cache:
      enabled: true
      cookies: ['/^SS?ESS/', '/^Drupal.visitor/']
"https://history.as.cornell.edu/":
    type: upstream
    upstream: "app:http"
    cache:
      enabled: true
      cookies: ['/^SS?ESS/', '/^Drupal.visitor/']
"https://icmdev.as.cornell.edu/":
    type: upstream
    upstream: "app:http"
    cache:
      enabled: true
      cookies: ['/^SS?ESS/', '/^Drupal.visitor/']
"https://linguistics.as.cornell.edu/":
    type: upstream
    upstream: "app:http"
    cache:
      enabled: true
      cookies: ['/^SS?ESS/', '/^Drupal.visitor/']
"https://mbg.as.cornell.edu/":
    type: upstream
    upstream: "app:http"
    cache:
      enabled: true
      cookies: ['/^SS?ESS/', '/^Drupal.visitor/']
"https://music.as.cornell.edu/":
    type: upstream
    upstream: "app:http"
    cache:
      enabled: true
      cookies: ['/^SS?ESS/', '/^Drupal.visitor/']
"https://nbb.as.cornell.edu/":
    type: upstream
    upstream: "app:http"
    cache:
      enabled: true
      cookies: ['/^SS?ESS/', '/^Drupal.visitor/']
"https://philosophy.as.cornell.edu/":
    type: upstream
    upstream: "app:http"
    cache:
      enabled: true
      cookies: ['/^SS?ESS/', '/^Drupal.visitor/']
"https://romancestudies.as.cornell.edu/":
    type: upstream
    upstream: "app:http"
    cache:
      enabled: true
      cookies: ['/^SS?ESS/', '/^Drupal.visitor/']
"https://sts.as.cornell.edu/":
    type: upstream
    upstream: "app:http"
    cache:
      enabled: true
      cookies: ['/^SS?ESS/', '/^Drupal.visitor/']
